# -*- coding: utf-8 -*-
"""Aula_5_Fabio_Natan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YNtKVAO5GSmwRbVcQmW9xDGzmZ3O-AWE
"""

#Exercício 1
print("Exercício 1:")
aluno = input("Digite o nome do estudante: ")
nota1 = float(input("Informe a 1º nota do estudante: "))
nota2 = float(input("Informe a 2º nota do estudante: "))
nota3 = float(input("Informe a 3º nota do estudante: "))
media = float(nota1 + nota2 + nota3) / 3

if media >= 7:
  print("O(A) estudante",aluno,"está aprovado pois sua média é:", media)
elif media <= 5:
  print("O(A) estudante",aluno,"está reprovado pois sua média é:", media)
else:
  print("O(A) estudante",aluno,"está de recuperação pois sua média é:", media)


#Exercício 2
print("Exercício 2:")
incogX = input("Digite o valor da incógnita ""X"": ")
incogY = input("Digite o valor da incógnita ""Y"": ")

if incogX > incogY:
  print("A incógnita X:",incogX,"é maior que a incógnita Y:", incogY)
else:
  print("A incógnita Y:",incogY,"é maior que a incógnita X:", incogX)


#Exercício 3
print("Exercício 3:")
genero = input("Escolha um sexo, \"M\" para masculino e \"F\" para feminino: ")
masc = "M"
femi = "F"

if genero == masc:
  print("Sexo válido!")
elif genero == femi:
  print("Sexo válido!")
else:
  print("Sexo inválido!")



#Exercício 4
print("Exercício 4:")
incogA = int(input("Digite um número inteiro que representará a incógnita \"a\": "))
incogB = int(input("Digite um número inteiro que representará a incógnita \"b\": "))
diferencaA = incogA - incogB
diferencaB = incogB - incogA

if incogA > incogB:
 print("A diferença da incógnita A:",incogA,"da incógnita B:",incogB,"é de:", diferencaA)
if incogB > incogA:
 print("A diferença da incógnita B:",incogB,"da incógnita A:",incogA,"é de:", diferencaB)


#Exercício 5 & 6
print("Exercício 5 & 6:")
sexoM = "M"
sexoF = "F"

while True:           #Aqui eu utilizo o while para repetir o algoritmo toda vez que o usuário colocar uma informação que não seja um núm. de 0 a 10 professor.
  nota_1 = int(input("Digite a 1° nota (de 0 a 10) do(a) aluno(a): "))
  nota_2 = int(input("Digite a 2° nota (de 0 a 10) do(a) aluno(a): "))
  nota_3 = int(input("Digite a 3° nota (de 0 a 10) do(a) aluno(a): "))
  nota_4 = int(input("Digite a 4° nota (de 0 a 10) do(a) aluno(a): "))
  media_5_6 = float(nota_1 + nota_2 + nota_3 + nota_4) / 4
  if 0 <= nota_1 <= 10:
    break
  elif 0 <= nota_2 <= 10:
    break
  elif 0 <= nota_3 <= 10:
    break
  elif 0 <= nota_4 <= 10:
    break
  else:
    print("Por favor, digite um número de 0 a 10.")
    continue

while True:          #O while tem a mesma função, mas agora o algor. irá repetir se o usuário escrever qlqr coisa que não seja a letra "M" ou "F"
  sexo = input("Qual o sexo do aluno? (\"M\" para masculino e \"F\" para feminino): ")
  if sexo == sexoM and media_5_6 >= 6:
    print("Caro aluno, seu resultado é aprovado!")
    break
  elif sexo == sexoM and media_5_6 < 6:
    print("Caro aluno, seu resultado é reprovado!")
    break
  elif sexo == sexoF and media_5_6 >= 6:
    print("Cara aluna, seu resultado é aprovada!")
    break
  elif sexo == sexoF and media_5_6 < 6:
    print("Cara aluna, seu resultado é reprovada!")
  else:
    print("Por favor, digite \"M\" ou \"F\" para definir o sexo do aluno")
    continue


#Exercício 7
print("Exercício 7:")
incog1 = int(input("Digite um número inteiro: "))

if incog1 >= 0:
  print("O número",incog1,"é positivo!")
else:
  print("O número",incog1,"é negativo!")


#Exercício Extra
print("Exercício extra:")
x = float(input("Digite um valor para o comprimento \"X\" do triângulo: "))
y = float(input("Digite um valor para o comprimento \"Y\" do triângulo: "))
z = float(input("Digite um valor para o comprimento \"Z\" do triângulo: "))

if (x + y < z) or (y + z < x) or (z + x < y):
  print("Isso não é um triângulo!")
elif (x == y) and (x == z):
  print("Isso é um um triângulo equilátero pois os 3 lados possuem comprimentos são iguais.")
elif (x == y) or (y == z) or (z == x):
  print("Isso é um triângulo isósceles pois 2 lados possuem o mesmo comprimento.")
else:
  print("Isso é um triângulo escaleno pois os 3 lados possuem o comprimento diferente.")